# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "pipeline" ]
  pull_request:
    branches: [ "master", "pipeline" ]

jobs:
  build-native:
    strategy:
      matrix:
        target: [ linux-x64, linux-x86, linux-arm64, linux-armv7 ]
    runs-on: ubuntu-latest
    container:
      image: dockcross/${{matrix.target}}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: create build folder
      run: mkdir -p build/${{matrix.target}}
    - name: cmake config
      run: cmake -DCMAKE_BUILD_TYPE=Release ../WireGuard.Native
      working-directory: ./build/${{matrix.target}}
    - name: build
      run: cmake --build . --parallel
      working-directory: ./build/${{matrix.target}}
    - name: Archive .so
      uses: actions/upload-artifact@v3
      with:
        name: libwireguard
        path: ./*/libwireguard.so
        if-no-files-found: error
        working-directory: ./build
  build-dotnet:
    needs: build-native
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: libwireguard
          path: ./build-native
      - name: Copy library files
        run: |
          ls */*
      #     mkdir build-native
      #     mkdir build-native/linux-arm64
      #     mv build-linux-arm64/libwireguard.so build-native/linux-arm64
      #     mkdir build-native/linux-arm
      #     mv build-linux-armv7/libwireguard.so build-native/linux-arm
      #     mkdir build-native/linux-x64
      #     mv build-linux-x64/libwireguard.so build-native/linux-x64
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build release
        run: dotnet build --no-restore --configuration Release
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
