# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "pipeline" ]
  pull_request:
    branches: [ "master", "pipeline" ]

jobs:
  build-native:
    runs-on: ubuntu-latest
    container:
      image: dockcross/linux-arm64
    steps:
    - uses: actions/checkout@v3
    - name: cmake config
      run: cmake -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build --parallel
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 6.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
  # build-native2:
  #   strategy:
  #     matrix:
  #       runtime: [ linux-x64, linux-arm64, linux-arm ]
  #       include:
  #       - runtime: linux-x64
  #         os: ubuntu-latest
  #       - runtime: linux-arm64
  #         os: ubuntu-latest
  #       - runtime: linux-arm
  #         os: ubuntu-latest
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - name: Configure and build native
  #       uses: threeal/cmake-action@latest 
